#! /bin/bash
#
#

CONTAINER="[willtack/hasl]"
echo -e "$CONTAINER  Initiated"

# Built to flywheel-v0 spec.
FLYWHEEL_BASE=/flywheel/v0
MCR_ROOT=/usr/local/MATLAB/MATLAB_Runtime/v96/  # double check this
INPUT_DIR=${FLYWHEEL_BASE}/input
OUTPUT_DIR=${FLYWHEEL_BASE}/output
CODE_DIR=${FLYWHEEL_BASE}/app/for_testing

# Make sure that /output directory exists
if [[ ! -d "${OUTPUT_DIR}" ]]
    then
        echo "${CONTAINER}  ${OUTPUT_DIR} not found!"
        exit 1
fi

# Set paths to input files
aslFile=$(find ${INPUT_DIR}/asl/ -type f | grep .nii)
m0File=$(find ${INPUT_DIR}/m0/ -type f | grep .nii)
mprageFile=$(find ${INPUT_DIR}/mprage/ | grep .nii)

# Check for required inputs
if [[ -z "$aslFile" ]] ||  [[ -z "$m0File" ]] || [[ -z "$mprageFile" ]]; then
  echo -e "$CONTAINER  One or more input files were not found! Exiting!"
  exit 1
fi

ls -Rl ${INPUT_DIR}
ls -al

# Run the Matlab executable
time ${CODE_DIR}/run_full_analysis.sh "${MCR_ROOT}"\
                                      "${aslFile}"\
                                      "${m0File}"\
                                      "${mprageFile}"\
                                      "${OUTPUT_DIR}"

# Check exit status
exit_status=$?
if [[ $exit_status != 0 ]]; then
  echo -e "$CONTAINER  An error occurred during execution of the Matlab executable. Exiting!"
  exit 1
fi

# Get a list of the files in the output directory
outputs=$(find $OUTPUT_DIR/* -maxdepth 0 -type f)

# If outputs exist, generate metadata, and exit
if [[ -z $outputs ]]; then
  echo "$CONTAINER  No results found in output directory... Exiting"
  exit 1
else
  cd $OUTPUT_DIR
  rm -rf MPRAGE ASL M0 # remove the intermediate directories. just keep the derived maps
  echo -e "$CONTAINER  Wrote: `ls`"
  echo -e "$CONTAINER  Done!"
fi

# Exit
exit 0
